---
version: '3.8'
services:

  bot: &emlyon_base
    image: lucmichalski/emlyon-telegram-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - db-data:/opt/em-lyon/store 

  crawler:
    <<: *emlyon_base
    volumes:
    - em-data:/opt/em-lyon/data
    - em-cache:/opt/em-lyon/cache
    command: ["crawl", "--data-dir", "/opt/em-lyon/data", "--cache-dir", "/opt/em-lyon/cache", "--data-reset"]

  telegram:
    <<: *emlyon_base
    command: ["chatbot"]

  rest:
    image: lucmichalski/emlyon-qa-server:guicorn-latest
    container_name: ${NAMESPACE}-gunicorn
    build:
      context: .docker/haystack-rest
      dockerfile: Dockerfile
    environment:
    - DB_HOST=elastic
    - DB_INDEX=em-lyon
    - PROJECT_NAME="EM Lyom - QA Telegram"
    networks:
    - internal
    - web
    ports:
    - 8000:8000
    depends_on:
    - elastic
    - tika
    command: ["gunicorn", "application:app",  "-b", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker", "--workers", "2", "--timeout", "180"]    

  gpt2bot:
    container_name: ${NAMESPACE}-gpt2bot
    image: lucmichalski/emlyon-qa-gpt2bot:latest
    build:
      context: .docker/gpt2bot
      dockerfile: Dockerfile.gpu
    networks:
    - internal
    - web
    volumes:
    - ./shared/logs:/opt/logs
    ports:
    - 5011:5011

  deeppavlov:
    container_name: ${NAMESPACE}-deeppavlov
    image: lucmichalski/emlyon-qa-deeppavlov:latest
    build:
      context: .docker/deeppavlov-chatbot/nlu
      dockerfile: Dockerfile
    networks:
    - internal
    - web
    ports:
    - 5000:5000
    command: [ "python", "-m", "deeppavlov", "riseapi", "model_config.json", "-p", "5000" ]

  # server:
  #   container_name: ${NAMESPACE}-flask
  #   image: lucmichalski/emlyon-qa-server:flask-latest
  #   build:
  #     context: .docker/haystack-flask
  #     dockerfile: Dockerfile.gpu
  #   networks:
  #   - internal
  #   - web
  #   volumes:
  #   - ./shared/logs:/opt/logs
  #   ports:
  #   - 8001:8001
  #   depends_on:
  #   - elastic
  #   - tika
  #   command: ["--port", "8001", "--host", "0.0.0.0"]

  server: &emlyon_server
    container_name: ${NAMESPACE}-server
    image: lucmichalski/emlyon-textqa-chatbot-server:flask-latest
    build:
      context: .docker/haystack-flask
      dockerfile: Dockerfile.gpu
    networks:
    - internal
    - web
    volumes:
    - ./shared/logs:/opt/logs
    - em-models:/root/.cache/
    depends_on:
    - elastic
    - tika

  server-en:
    <<: *emlyon_server    
    container_name: ${NAMESPACE}-server_en
    ports:
    - 8006:8006
    command: ["--port", "8006", "--host", "0.0.0.0", "--model", "deepset/roberta-base-squad2"]

  server-fr:
    <<: *emlyon_server    
    container_name: ${NAMESPACE}-server_fr
    ports:
    - 8007:8007
    command: ["--port", "8007", "--host", "0.0.0.0", "--model", "illuin/camembert-base-fquad"]

  train: &emlyon_train
    container_name: ${NAMESPACE}-train
    build:
      context: .docker/haystack-train
      dockerfile: Dockerfile
    networks:
    - internal
    volumes:
    - em-data:/opt/em-lyon/data
    depends_on:
    - elastic
    - tika

  train-en:
    <<: *emlyon_train    
    container_name: ${NAMESPACE}-train_en-us
    command: ["--data-dir", "/opt/em-lyon/data/en", "--index-name", "emlyon-en", "--index-reset"]

  train-fr:
    <<: *emlyon_train    
    container_name: ${NAMESPACE}-train_en-us
    command: ["--data-dir", "/opt/em-lyon/data/fr", "--index-name", "emlyon-fr", "--index-reset"]

  elastic:
    image: elasticsearch:7.6.2
    container_name: ${NAMESPACE}-elastic
    networks:
    - internal
    environment:
    - discovery.type=single-node
    volumes:
    - es-data:/usr/share/elasticsearch/data
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

  tika:
    image: lucmichalski/apachae-tika:alpine3.12-1.24.1
    container_name: ${NAMESPACE}-tika
    build:
      context: .docker/alpine-tika
      dockerfile: Dockerfile
    networks:
    - internal
    volumes:
    - tika-data:/var/tika
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  em-models:
  em-data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared/data/emlyon
  em-cache:
  db-data:
  es-data:
  tika-data:


