---
version: '3.8'
services:

  bot: &emlyon_base
    image: lucmichalski/emlyon-telegram-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - db-data:/opt/em-lyon/store 

  crawler:
    <<: *emlyon_base
    volumes:
    - em-data:/opt/em-lyon/data
    - em-cache:/opt/em-lyon/cache
    command: ["crawl", "--data-dir", "/opt/em-lyon/data", "--cache-dir", "/opt/em-lyon/cache", "--data-reset"]

  telegram:
    <<: *emlyon_base
    command: ["chatbot"]

  rest:
    image: lucmichalski/emlyon-qa-server:guicorn-latest
    container_name: ${NAMESPACE}-gunicorn
    build:
      context: .docker/haystack-rest
      dockerfile: Dockerfile
    environment:
    - DB_HOST=elastic
    - DB_INDEX=em-lyon
    - PROJECT_NAME="EM Lyom - QA Telegram"
    networks:
    - internal
    - web
    ports:
    - 8000:8000
    depends_on:
    - elastic
    - tika
    command: ["gunicorn", "application:app",  "-b", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker", "--workers", "2", "--timeout", "180"]    

  deeppavlov:
    container_name: ${NAMESPACE}-deeppavlov
    image: lucmichalski/emlyon-qa-deeppavlov:latest
    build:
      context: .docker/deeppavlov-chatbot/nlu
      dockerfile: Dockerfile
    networks:
    - internal
    - web
    ports:
    - 5000:5000
    command: [ "python", "-m", "deeppavlov", "riseapi", "model_config.json", "-p", "5000" ]

  server:
    container_name: ${NAMESPACE}-flask
    image: lucmichalski/emlyon-qa-server:flask-latest
    build:
      context: .docker/haystack-flask
      dockerfile: Dockerfile
    networks:
    - internal
    - web
    volumes:
    - ./shared/logs:/opt/logs
    ports:
    - 8001:8001
    depends_on:
    - elastic
    - tika
    command: ["--port", "8001", "--host", "0.0.0.0"]

  train:
    container_name: ${NAMESPACE}-train
    build:
      context: .docker/haystack-train
      dockerfile: Dockerfile
    networks:
    - internal
    volumes:
    - em-data:/opt/em-lyon/data
    depends_on:
    - elastic
    - tika
    command: ["python3", "train.py", "--index-reset", "--data-dir", "/opt/em-lyon/data/en"]

  elastic:
    image: elasticsearch:7.6.2
    container_name: ${NAMESPACE}-elastic
    networks:
    - internal
    environment:
    - discovery.type=single-node
    volumes:
    - es-data:/usr/share/elasticsearch/data
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

  tika:
    image: lucmichalski/apachae-tika:alpine3.12-1.24.1
    container_name: ${NAMESPACE}-tika
    build:
      context: .docker/alpine-tika
      dockerfile: Dockerfile
    networks:
    - internal
    volumes:
    - tika-data:/var/tika
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  em-data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared/data/emlyon
  em-cache:
  db-data:
  es-data:
  tika-data:


