---
version: '3.8'
services:
  
  dp:
    container_name: dp-finance
    image: lucmichalski/dp-finance:gpu-latest
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
    - 5000:5000
    volumes:
    - dp-data:/opt/data
    - ${PWD}:/usr/src/app

volumes:
  dp-data:
  
